/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "event_groups.h"
#include "timers.h"

#include "globals.h"
#include "tasks.h"
#include "main.h"
#include "rcc.h"
#include "gpio.h"
#include "spi.h"
#include "st7735.h"
#include "i2c.h"
#include "nunchuck.h"
#include "display.h"
#include "aht10.h"
#include "rtc.h"
#include "tim.h"
#include "assets.h"
#include "at24cxx.h"

static void initialise_fpu(void){
	SCB->CPACR |= ((3UL << 10*2) | (3UL << 11*2));
	__DSB();
	__ISB();
}

void errorHandler(void){
    for(;;){
    	led_off(LED_STATUS_PIN, LED_STATUS_GPIO);
    	delay_ms(100);
    	led_on(LED_STATUS_PIN, LED_STATUS_GPIO);
    	delay_ms(100);
    }
}

QueueHandle_t xDisplayQueue;
SemaphoreHandle_t xNunchuckDataMutex;
EventGroupHandle_t xSystemFlags;

NunchuckData_t g_nun_data;

int main(void)
{
	initialise_fpu();
	initialize_clocks();
	tim2_1hz_init();
	spi1_init();
	spi_dma_init();
	init_leds();
	i2c1_init();
	ST7735_Init();
	nunchuck_init();
	aht10_init();
	rtc_init();
	srand(RTC->TR ^ RTC->DR);

	BaseType_t ret;

	xDisplayQueue = xQueueCreate(20, sizeof(displayData_t));
	if(xDisplayQueue == NULL){
		errorHandler();
	}

	xNunchuckDataMutex = xSemaphoreCreateMutex();
	if(xNunchuckDataMutex == NULL){
		errorHandler();
	}

	xSystemFlags = xEventGroupCreate();
	if(xSystemFlags == NULL){
		errorHandler();
	}

	xEventGroupSetBits(xSystemFlags, HOME_SCREEN);

	ret = xTaskCreate(vHomeTask, "Home Task", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vDisplayTask, "Display Task", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vReadNunchuckTask, "Nunchuck Task", configMINIMAL_STACK_SIZE * 2, NULL, 4, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vDisplayRTCTask, "RTC Task", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vMenuTask, "Menu Task", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vPingPongTask, "Ping Pong Task", configMINIMAL_STACK_SIZE * 4, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vAirRace, "Air Race Task", configMINIMAL_STACK_SIZE * 6, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}

	ret = xTaskCreate(vSettingsTask, "Settings Task", configMINIMAL_STACK_SIZE * 3, NULL, 3, NULL);
	if(ret != pdPASS) {
		errorHandler();
	}

	ret = xTaskCreate(vUpdateDateTimeTask, "DateTime Task", configMINIMAL_STACK_SIZE * 2, NULL, 3, NULL);
	if(ret != pdPASS){
		errorHandler();
	}


	vTaskStartScheduler();

	while(1){
		uint8_t data[5];
		at_read_data((uint8_t *)data, sizeof(data));
		delay_ms(10);
	}
}

void vHomeTask(void * pvParameters){

	displayData_t msg;
	msg.data_type = TEXT;
	msg.text.bgColor = ST7735_BLACK;

	displayData_t clear_rect;
	clear_rect.x = 0;
	clear_rect.y = 0;
	clear_rect.data_type = RECT;
	clear_rect.rect.color = ST7735_BLACK;
	clear_rect.rect.w = DISPLAY_WIDTH;
	clear_rect.rect.h = DISPLAY_HEIGHT;

	while(1){
		xEventGroupWaitBits(xSystemFlags, HOME_SCREEN, pdFALSE, pdTRUE, portMAX_DELAY);

		xQueueSend(xDisplayQueue, &clear_rect, portMAX_DELAY);

		snprintf(msg.text.str, sizeof(msg.text.str), "AZRAEL");
		msg.x = 20;
		msg.y = 5;
		msg.text.color = ST7735_BLUE;
		msg.text.font = &Font_16x26;
    	xQueueSend(xDisplayQueue, &msg, portMAX_DELAY);
    	vTaskDelay(pdMS_TO_TICKS(16));

    	snprintf(msg.text.str, sizeof(msg.text.str), "Gaming");
    	msg.x = 33;
    	msg.y = 35;
    	msg.text.color = ST7735_WHITE;
    	msg.text.font = &Font_11x18;
    	xQueueSend(xDisplayQueue, &msg, portMAX_DELAY);

    	snprintf(msg.text.str, sizeof(msg.text.str), "Console");
    	msg.x = 28;
    	msg.y = 55;
    	msg.text.color = ST7735_WHITE;
    	msg.text.font = &Font_11x18;
    	xQueueSend(xDisplayQueue, &msg, portMAX_DELAY);

    	snprintf(msg.text.str, sizeof(msg.text.str), "press OK/Z to continue");
    	msg.x = 0;
		msg.y = 150;
		msg.text.color = ST7735_RED;
		msg.text.font = &Font_7x10;
		xQueueSend(xDisplayQueue, &msg, portMAX_DELAY);

		EventBits_t uxBits = xEventGroupWaitBits(xSystemFlags, OK_PRESSED, pdTRUE, pdFALSE, portMAX_DELAY);

		if(uxBits & OK_PRESSED){
			xEventGroupClearBits(xSystemFlags, HOME_SCREEN);
			xEventGroupSetBits(xSystemFlags, MENU_SCREEN);
		}

    	vTaskDelay(pdMS_TO_TICKS(16));
	}
}

void vDisplayTask(void * pvParameters){

	displayData_t data;

	while(1){

		while(xQueueReceive(xDisplayQueue, &data, pdMS_TO_TICKS(16)) == pdTRUE){
			switch (data.data_type){
				case TEXT:
					display_write_string(data.x, data.y, data.text.str, *data.text.font, data.text.color, data.text.bgColor);
					break;
				case RECT:
					display_fill_rect(data.x, data.y, data.rect.w, data.rect.h, data.rect.color);
					break;
				case CIRCLE:
					display_draw_circle(data.x, data.y, data.circle.r, data.circle.color);
					break;
				case IMAGE:
					display_draw_image(data.x, data.y, data.image.w, data.image.h, data.image.image);
					break;
				default:
					break;
			}
		}

		display_flush();
	}
}

void vReadNunchuckTask(void * pvParameters){

	NunchuckData_t nun_data;

	uint8_t prev_z_btn_press = 0, curr_z_btn_press;
	uint8_t prev_c_btn_press = 0, curr_c_btn_press;

	while(1){
		nunchuck_read(&nun_data);
		xSemaphoreTake(xNunchuckDataMutex, portMAX_DELAY);
		g_nun_data = nun_data;
		xSemaphoreGive(xNunchuckDataMutex);

		curr_z_btn_press = nun_data.btn_z;
		curr_c_btn_press = nun_data.btn_c;

		if(prev_z_btn_press != curr_z_btn_press){
			if(curr_z_btn_press) xEventGroupSetBits(xSystemFlags, OK_PRESSED);
			prev_z_btn_press = curr_z_btn_press;
		} else if (prev_c_btn_press != curr_c_btn_press){
			if(curr_c_btn_press) xEventGroupSetBits(xSystemFlags, EXIT_PRESSED);
			prev_c_btn_press = curr_c_btn_press;
		}
		vTaskDelay(pdMS_TO_TICKS(16));
	}
}

void vDisplayRTCTask(void * pvParameters){

	struct tm datetime;
	displayData_t data;
	data.data_type = TEXT;
	data.text.color = ST7735_MAGENTA;
	data.text.bgColor = ST7735_BLACK;

	while(1){
		xEventGroupWaitBits(xSystemFlags, HOME_SCREEN, pdFALSE, pdTRUE, portMAX_DELAY);

		rtc_get_dateTime(&datetime);

		strftime(data.text.str, sizeof(data.text.str), "%I: %M %p", &datetime);
		data.x = 20;
		data.y = 85;
		data.text.font = &Font_11x18;
		xQueueSend(xDisplayQueue, &data, portMAX_DELAY);

		strftime(data.text.str, sizeof(data.text.str), "%A %d %B", &datetime);
		data.x = (DISPLAY_WIDTH - (strlen(data.text.str) * 7)) / 2;
		data.y = 105;
		data.text.font = &Font_7x10;
		xQueueSend(xDisplayQueue, &data, portMAX_DELAY);

		vTaskDelay(pdMS_TO_TICKS(1000));
	}
}

void vMenuTask(void * pvParameters){

	displayData_t data;
	data.data_type = TEXT;
	data.y = 75;
	data.x = 20;
	data.text.color = ST7735_WHITE;
	data.text.bgColor = ST7735_BLUE;
	data.text.font = &Font_11x18;

	displayData_t clear_rect;
	clear_rect.x = 0;
	clear_rect.y = 0;
	clear_rect.data_type = RECT;
	clear_rect.rect.color = ST7735_BLACK;
	clear_rect.rect.w = DISPLAY_WIDTH;
	clear_rect.rect.h = DISPLAY_HEIGHT;

	displayData_t des_rect;
	des_rect.x = 14;
	des_rect.y = 40;
	des_rect.data_type = RECT;
	des_rect.rect.color = ST7735_BLUE;
	des_rect.rect.w = 100;
	des_rect.rect.h = 80;


	NunchuckData_t nun_data;
	uint8_t joy_data_dir = 0;
	uint8_t prev_joy_data_dir = 0;
	int8_t menu_pos = 0;

	while(1){
		xEventGroupWaitBits(xSystemFlags, MENU_SCREEN, pdFALSE, pdTRUE, portMAX_DELAY);
		xSemaphoreTake(xNunchuckDataMutex, portMAX_DELAY);
		nun_data = g_nun_data;
		xSemaphoreGive(xNunchuckDataMutex);

		if(menu_pos > 2) menu_pos = 0;
		if(menu_pos < 0) menu_pos = 2;

		if(nun_data.joy_x < 30){
			joy_data_dir = 2;
		} else if(nun_data.joy_x > 225){
			joy_data_dir = 1;
		} else {
			joy_data_dir = 0;
		}

		if(prev_joy_data_dir != joy_data_dir){
			if(joy_data_dir == 1){
				menu_pos++;
			}else if(joy_data_dir == 2){
				menu_pos--;
			}
			prev_joy_data_dir = joy_data_dir;
		}

		xQueueSend(xDisplayQueue, &clear_rect, portMAX_DELAY);
		xQueueSend(xDisplayQueue, &des_rect, portMAX_DELAY);

		data.y = 5;
		data.x = 27;
		data.text.color = ST7735_WHITE;
		data.text.bgColor = ST7735_BLACK;
		data.text.font = &Font_16x26;
		snprintf(data.text.str, sizeof(data.text.str), "MENU");
		xQueueSend(xDisplayQueue, &data, portMAX_DELAY);

		data.y = 75;
		data.x = 20;
		data.text.color = ST7735_WHITE;
		data.text.bgColor = ST7735_BLUE;
		data.text.font = &Font_11x18;

		switch(menu_pos){
		case 0:
			snprintf(data.text.str, sizeof(data.text.str), "SETTINGS");
			xQueueSend(xDisplayQueue, &data, portMAX_DELAY);
			break;
		case 1:
			snprintf(data.text.str, sizeof(data.text.str), "PING PONG");
			xQueueSend(xDisplayQueue, &data, portMAX_DELAY);
			break;
		case 2:
			snprintf(data.text.str, sizeof(data.text.str), "AIR RACE");
			xQueueSend(xDisplayQueue, &data, portMAX_DELAY);
			break;
		default:
			break;
		}

		EventBits_t uxBits = xEventGroupWaitBits(xSystemFlags, OK_PRESSED | EXIT_PRESSED, pdTRUE, pdFALSE, pdMS_TO_TICKS(5));

		if(uxBits & OK_PRESSED){
			xEventGroupClearBits(xSystemFlags, MENU_SCREEN);
			if(menu_pos == 1){
				xEventGroupSetBits(xSystemFlags, PING_PONG_SCREEN);
			}else if(menu_pos == 2){
				xEventGroupSetBits(xSystemFlags, AIR_RACE_SCREEN);
			} else if(menu_pos == 0) { xEventGroupSetBits(xSystemFlags, SETTINGS_SCREEN); }
		}else if(uxBits & EXIT_PRESSED){
			xEventGroupClearBits(xSystemFlags, MENU_SCREEN);
			xEventGroupSetBits(xSystemFlags, HOME_SCREEN);
		}
		vTaskDelay(pdMS_TO_TICKS(16));
	}
}


void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    (void)xTask;
    (void)pcTaskName;
    taskDISABLE_INTERRUPTS();
    for(;;){
    	led_off(LED_STATUS_PIN, LED_STATUS_GPIO);
    	delay_ms(100);
    	led_on(LED_STATUS_PIN, LED_STATUS_GPIO);
    	delay_ms(100);
    }
}


void vApplicationMallocFailedHook(void) {
    taskDISABLE_INTERRUPTS();
    for(;;){
    	led_on(LED_GREEN_PIN, LED_GREEN_GPIO);
    	delay_ms(100);
    	led_off(LED_GREEN_PIN, LED_GREEN_GPIO);
    	delay_ms(100);
    }
}
