/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "gpio.h"
#include "systick.h"
#include "tim.h"
#include "uart.h"
#include "adc.h"
#include "i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

bool btn_state;
int sensor_value;

char data[1];

int main(void)
{
    /* Loop forever */
	led_init();
	button_init();
	tim2_1hz_init();
	uart_init();
	pa1_adc_init();
	start_conversion();
	i2c1_init();


	while(1){
		i2c1_byte_read(0x38, 0xE1, data);
		printf("Hello from stm32...\r\n");
		sensor_value = adc_read();
		printf("Sensor Value: %d\r\n", sensor_value);
		led_toggle();
		while(!(TIM2->SR & SR_UIF)){}
		TIM2->SR &= ~SR_UIF;
	}
}
